### ISSUE TITLE
Regarding usage of Data

### ISSUE THREAD

**Issue by abhisekpraharaj** [pierinim/tutorials#4]
Respected Sir, I am a MS physics student currently getting into High Energy Physics.  I would like to ask for permission to use this jet dataset for my educational purposes like doing some more deep learning applications on it.

**Comment by pierinim** [comment]
Hello. This dataset is part of a larger dataset, which is publicly available on Zenodo. You can certainly use this dataset or the entire one, and (if needed) cite the doi of the Zenodo data

https://zenodo.org/record/3602260#.YuGU-hbRbDs

**Comment by abhisekpraharaj** [comment]
Thank You Sir!
